source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

gem 'rails', '~> 5.2.0'
gem 'pg'
gem 'puma'
gem 'sass-rails'
gem 'webpacker'
gem 'turbolinks'
gem 'jbuilder'
gem 'bootsnap'
gem 'bower-rails',  '~> 0.11.0'
gem 'sinclair',     '~> 1.5.1'
gem 'tarquinn',     '0.1.0'
gem 'darthjee-core_ext', '>= 2.0.0'
gem 'newrelic_rpm', '~> 6.2.x'
gem 'rake',         '>= 12.3.1'

group :development do
  # Access an interactive console on exception pages
  # or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your
  # application running in the background.
  # Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'factory_bot',   '5.0.2'
  gem 'pry-nav',       '~> 0.2.4'
  gem 'pry-rails',     '0.3.9'
  gem 'rspec',         '>= 3.8'
  gem 'rspec-rails',   '3.8.2'
  gem 'rubocop',       '0.58.1'
  gem 'rubocop-rspec', '1.30.0'
  gem 'rubycritic',    '>= 4.0.2'
  gem 'simplecov',     '~> 0.16.x'
  gem 'yard',          '>= 0.9.18'
  gem 'yardstick',     '>= 0.9.9'
  gem 'zonebie',       '0.6.1'

end

group :development, :test do
  gem 'web-console', '>= 3.3.0'
  gem 'timecop', '0.9.1'

  gem 'rails-controller-testing', '1.0.4'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'webmock', '3.5.1'

  gem 'database_cleaner'
  gem 'rspec-collection_matchers', '1.1.3'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
